<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5a840646a1d68',
	'title' => 'Template Builder',
	'fields' => array(
		array(
			'key' => 'field_5a84065f876ad',
			'label' => 'Template Builder',
			'name' => 'template_builder',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5a9e5f03cfca5' => array(
					'key' => '5a9e5f03cfca5',
					'name' => 'hero_banner',
					'label' => 'Hero Banner',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5a9e5f8fcfca9',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '1800 x 600 px',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5a9e5fb9cfcab',
							'label' => 'Intro Heading',
							'name' => 'second_heading',
							'type' => 'text',
							'instructions' => 'Small yellow heading. Leave blank if not needed.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5a9e5fa5cfcaa',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => 'Main large heading.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5a4f9fa5cfcaa',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'text',
							'instructions' => 'Small description copy displayed under main heading. Leave blamk if not needed.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59c8884b3b0',
							'label' => 'Link URL',
							'name' => 'link_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				/*
				'd7v45f03cfca5' => array(
					'key' => 'd7v45f03cfca5',
					'name' => 'intro_block',
					'label' => 'Intro Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5a7p5hb9cfcab',
							'label' => 'Block Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => 'This title is slanted and is inside a block',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),

						array(
							'key' => 'field_5z4z79e4b3d6f',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => 'Select the background colour used for this block',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'section' => 'Section',
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
								0 => 'white',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5a9f1hb9cfcab',
							'label' => 'Intro Content',
							'name' => 'intro_content',
							'type' => 'text',
							'instructions' => 'This is the content which appears under the block title',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				*/
				'layout_5b59b74baee50' => array(
					'key' => 'layout_5b59b74baee50',
					'name' => 'latest_news',
					'label' => 'Latest News',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b59b778cd5bc',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59c9064b3ae',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5b59c9724b3af',
							'label' => 'Link Text',
							'name' => 'link_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59c9794b3b0',
							'label' => 'Link URL',
							'name' => 'link_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5b5eca14b9167',
							'label' => 'Section',
							'name' => 'section',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'section',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 1,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5a9d6b125f12a' => array(
					'key' => '5a9d6b125f12a',
					'name' => 'two_column_image_left',
					'label' => 'Two Column (Image/Video Left)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b59de39cc1fc',
							'label' => 'Content type',
							'name' => 'content_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'image' => 'Image',
								'video' => 'Video',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5a9d6b305f130',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'Image is needed whether image or video is set above. If Video, image is used as thumbnail. Image should be around 600x400px.',
							'required' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5b59deecb996f',
							'label' => 'Video URL',
							'name' => 'video_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5b59de39cc1fc',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5a9d6b125f12b',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5a9d6b125f12c',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59df1d8d9e2',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59df248d9e3',
							'label' => 'Button URL',
							'name' => 'button_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5a9d79e4b3d6f',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => 'Select the background colour used for this block',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'section' => 'Section',
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
								0 => 'white',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b59e89830c8b' => array(
					'key' => 'layout_5b59e89830c8b',
					'name' => 'two_column_image_right',
					'label' => 'Two Column (Image/Video right)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b59e89830c8c',
							'label' => 'Content type',
							'name' => 'content_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'image' => 'Image',
								'video' => 'Video',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_5b59e89830c8d',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'Image is needed whether image or video is set above. If Video, image is used as thumbnail. Image should be around 600x400px.',
							'required' => 0,

							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5b59e89830c8e',
							'label' => 'Video URL',
							'name' => 'video_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5b59e89830c8c',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5b59e89830c8f',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59e89830c90',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59e89830c91',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b59e89830c92',
							'label' => 'Button URL',
							'name' => 'button_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5b59e89830c93',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => 'Select the background colour used for this block',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'section' => 'Section',
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
								0 => 'white',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b19e72540c7c' => array(
					'key' => 'layout_5b59e17300c8c',
					'name' => 'full_width_content',
					'label' => 'Full-Width Content',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b8ff5bedf456',
							'label' => 'Below Hero Banner?',
							'name' => 'below_hero_banner',
							'type' => 'true_false',
							'instructions' => 'Enabling this will display the heading in a coloured box above the hero banner.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5b8ff5eedf457',
							'label' => 'Heading Colour',
							'name' => 'heading_colour',
							'type' => 'select',
							'instructions' => 'The background colour of the heading.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5b8ff5bedf456',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5b12e01222c1c',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b12e87090c11',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b90e99923b8b' => array(
					'key' => 'layout_5b90e77650c1b',
					'name' => 'content_with_sub_menu',
					'label' => 'Content With Sub-Menu',
					'display' => 'block',
					'sub_fields' => array(

						array(
							'key' => 'field_5b22e45311c2b',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5z22e67655c90',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_5b21eb03b904a',
							'label' => 'Sidebar Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => ' The sidebar will only display if this page has a parent. This can be set in the "Page Attributes" section to the right.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'section' => 'Section',
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5a9fc3a64f5fe' => array(
					'key' => '5a9fc3a64f5fe',
					'name' => 'call_to_action_block',
					'label' => 'Call To Action Block',
					'display' => 'block',
					'sub_fields' => array(
						/*
						array(
							'key' => 'field_5b59eb03b844a',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						*/
						array(
							'key' => 'field_5a9fc3da4f5ff',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => 'Recommended minimum width 1400px',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5a9fc3f64f600',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5a9fc3fe4f601',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5a9fc41a4f602',
							'label' => 'Buttons',
							'name' => 'buttons',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 2,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5a9fc4274f603',
									'label' => 'Button Text',
									'name' => 'button_text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5a9fc4354f605',
									'label' => 'Button Link',
									'name' => 'button_link',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'post_type' => array(
									),
									'taxonomy' => array(
									),
									'allow_null' => 0,
									'allow_archives' => 0,
									'multiple' => 0,
								),
								array(
									'key' => 'field_5b9106475f3dc',
									'label' => 'Button Type',
									'name' => 'button_type',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'normal' => 'Normal',
										'btn-video' => 'Video',
										'btn-donate' => 'Donate',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5adc1f8dce2' => array(
					'key' => 'layout_5b5adc1f8dce2',
					'name' => 'enquiry_form',
					'label' => 'Enquiry form',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5adc218dce3',
							'label' => 'Form ID',
							'name' => 'form_id',
							'type' => 'text',
							'instructions' => 'Enter the ID of the form you wish to display.',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						/*
						array(
							'key' => 'field_5b5ade4b5463a',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						*/
						array(
							'key' => 'field_5b5ade8776c8e',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5ae02bceac0' => array(
					'key' => 'layout_5b5ae02bceac0',
					'name' => 'image_gallery',
					'label' => 'Image Gallery',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5ae37fceac1',
							'label' => 'Gallery Item',
							'name' => 'gallery_item',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5b5ae488ceac2',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5ae7c806ec2' => array(
					'key' => 'layout_5b5ae7c806ec2',
					'name' => 'tiles',
					'label' => 'Tiles',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b90f155ac6a5',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b90f173b7ad8',
							'label' => 'Show Donate Button',
							'name' => 'show_donate_button',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5b90f1986b769',
							'label' => 'Donate Button Link',
							'name' => 'donate_button_link',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5b90f173b7ad8',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
						),
						array(
							'key' => 'field_5b5ae7c806ec3',
							'label' => 'Tile Items',
							'name' => 'tile_items',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5b5ae7c806ec4',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '600 x 400 px',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5b5ae7e706ec5',
									'label' => 'Heading',
									'name' => 'heading',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b5ae7f306ec6',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array(
									),
									'taxonomy' => array(
									),
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
								array(
									'key' => 'field_5b59c1554b3b0',
									'label' => 'Link URL',
									'name' => 'link_url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5b1f12b64dc' => array(
					'key' => 'layout_5b5b1f12b64dc',
					'name' => 'faqs',
					'label' => 'FAQs',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b2ae7e906ec2',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b5b1fa32d3e2',
							'label' => 'FAQ Items',
							'name' => 'faq_items',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'faqs',
							),
							'taxonomy' => array(
							),
							'filters' => array(
								0 => 'search',
								1 => 'taxonomy',
							),
							'elements' => '',
							'min' => '',
							'max' => '',
							'return_format' => 'object',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5h5b3f12q64dc' => array(
					'key' => 'layout_5b5b8d52b64dc',
					'name' => 'related_team',
					'label' => 'Selected Team Members',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b9hd7e906ec2',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b9hd7e887ec2',
							'label' => 'Intro Copy',
							'name' => 'intro',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b7575fc10285',
							'label' => 'Related Team Members',
							'name' => 'related_team',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'team',
							),
							'taxonomy' => array(
							),
							'filters' => array(
								0 => 'search',
								1 => 'taxonomy',
							),
							'elements' => '',
							'min' => '',
							'max' => '',
							'return_format' => 'object',
						),
						array(
							'key' => 'field_5b5fz33eb221f',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'section' => 'Section',
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_4h4b3f12q64dc' => array(
					'key' => 'layout_4h4b3f12q64dc',
					'name' => 'team-all',
					'label' => 'All the team',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_1c2hd7e906ec2',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_3m1hd7e887ec2',
							'label' => 'Intro Copy',
							'name' => 'intro',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_4q3fz33eb221f',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'section' => 'Section',
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5b31af7ddb4' => array(
					'key' => 'layout_5b5b31af7ddb4',
					'name' => 'testimonials',
					'label' => 'Testimonials',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b9132fda2362',
							'label' => 'Intro Heading',
							'name' => 'intro_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b91331b1525e',
							'label' => 'Intro Description',
							'name' => 'intro_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b5b31b87ddb5',
							'label' => 'Testimonial Items',
							'name' => 'testimonial_items',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'testimonials',
							),
							'taxonomy' => array(
							),
							'filters' => array(
								0 => 'search',
							),
							'elements' => '',
							'min' => '',
							'max' => '',
							'return_format' => 'object',
						),
						array(
							'key' => 'field_5b5ee65eb221f',
							'label' => 'Background Colour',
							'name' => 'background_colour',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'section' => 'Section',
								'white' => 'White',
								'#8dc63f' => 'Green',
								'#f3cc30' => 'Yellow',
								'#f7941d' => 'Orange',
								'#bf3051' => 'Burgundy',
								'#9dc9eb' => 'Light Blue',
								'#639144' => 'Dark Green',
								'#525c63' => 'Grey',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5ed23e0ecb0' => array(
					'key' => 'layout_5b5ed23e0ecb0',
					'name' => 'upcoming_events',
					'label' => 'Upcoming Events',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5ed2a80ecb1',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b5ed2af0ecb2',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5ed23e1ebb2' => array(
					'key' => 'layout_5b5ed23e1ebb2',
					'name' => 'documents',
					'label' => 'Documents',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5ed2a10ecb2',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b5b1fb23d1e9',
							'label' => 'Documents',
							'name' => 'documents',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'downloads',
							),
							'taxonomy' => array(
							),
							'filters' => array(
								0 => 'search',
								1 => 'taxonomy',
							),
							'elements' => '',
							'min' => '',
							'max' => '',
							'return_format' => 'object',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5b5edb336c2d6' => array(
					'key' => 'layout_5b5edb336c2d6',
					'name' => 'icon_blocks',
					'label' => 'Icon Blocks',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5edb426c2d7',
							'label' => 'Icon Block',
							'name' => 'icon_block',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5b5edb626c2d8',
									'label' => 'Icon',
									'name' => 'icon',
									'type' => 'text',
									'instructions' => 'Copy icon name from the Font Awesome website: https://fontawesome.com/icons/. Example: long-arrow-left',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b5edc630dc44',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b5edc670dc45',
									'label' => 'Text',
									'name' => 'text',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => '',
								),
								array(
									'key' => 'field_5b5edea9644a2',
									'label' => 'Icon Colour',
									'name' => 'icon_colour',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'#8dc63f' => 'Green',
										'#f3cc30' => 'Yellow',
										'#f7941d' => 'Orange',
										'#bf3051' => 'Burgundy',
										'#9dc9eb' => 'Light Blue',
										'#639144' => 'Dark Green',
										'#525c63' => 'Grey',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Content Block',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/flexible-template.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/page-jobs.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;
